[build]
builder = "DOCKERFILE"
dockerfilePath = "IdentityReportService/Dockerfile"

[deploy]
startCommand = "dotnet IdentityReportService.dll --urls http://0.0.0.0:$PORT"
healthcheckPath = "/swagger"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
